export const data = {
    global: {
        vesion: '0.0.3',
        uuid: null,
        type: 0,
        allowVideoElements: 1,
        combination: '1x1',
        orientation: 0,
        gap: 12,
        overlap: {},
        id: 104,
        name: '四分屏',
    },
    layouts: [
        {
            combination: '1x1',
            allowVideoElements: 1,
            top: 0,
            left: 0,
            width: 1920,
            height: 1080,
            materialSize: [1920, 1080],
            screenSize: [1920, 1080],
            orientation: 0,
            elements: [
                {
                    type: 'media',
                    x: 0,
                    y: 0,
                    width: 66.4583,
                    height: 100,
                    muted: true,
                    model: {
                        x: 0,
                        y: 0,
                        width: 66.4583,
                        height: 100,
                    },
                    data: [],
                },
                {
                    type: 'media',
                    x: 67.0833,
                    y: 0,
                    width: 32.9167,
                    height: 32.5926,
                    muted: true,
                    model: {
                        x: 67.0833,
                        y: 0,
                        width: 32.9167,
                        height: 32.5926,
                    },
                    data: [],
                },
                {
                    type: 'media',
                    x: 67.0833,
                    y: 33.7037,
                    width: 32.9167,
                    height: 32.5926,
                    muted: true,
                    model: {
                        x: 67.0833,
                        y: 33.7037,
                        width: 32.9167,
                        height: 32.5926,
                    },
                    data: [],
                },
                {
                    type: 'media',
                    x: 67.0833,
                    y: 67.4074,
                    width: 32.9167,
                    height: 32.5926,
                    muted: true,
                    model: {
                        x: 67.0833,
                        y: 67.4074,
                        width: 32.9167,
                        height: 32.5926,
                    },
                    data: [],
                },
            ],
        },
    ],
};
